irc_channel: "#orebotspam"
irc_host: "irc.esper.net"
irc_password: "REDACTED"
irc_discord_bot_name: "OREDiscord"
irc_network_bot_name: "ORENetwork"
discord_channel_id: "538879606527098900"
discord_irc_bot_token: "REDACTED"
discord_irc_bot_playing_message: "on the ORE Network"
discord_network_bot_token: "REDACTED"
discord_network_bot_playing_message: "on the ORE Network"
enable_special_quirky_message: false
quirky_message_frequency: 1000
enable_special_farewells_and_greetings: false
irc_to_discord_ignore_names:
  - "OREBot"
  - "OREDiscord"
  - "ORENetwork"
irc_to_game_ignore_names:
  - "OREDiscord"
  - "ORENetwork"
discord_ignore_ids:
  - "550377585192730634"
  - "550377656428920852"
  - "550377705389162496"
  - "550377749366177792"
  - "550378049183416341"
  - "550378104846286849"
  - "550378142662131712"
  - "552245840052486164"
  - "538878359401267202"
message_farewells:
  - "Come back soon!"
  - "We hope to see you soon!"
  - "Cya!"
  - "Don't forget to like and subscribe!"
message_greetings:
  - "glhf!"
  - "Everyone, look busy!"
  - "We were expecting you ( ͡° ͜ʖ ͡°)"
  - "We hope you brought pizza."
  - "Leave your weapons by the door."
  - "Hide the bananas!"
  - "Unleash the corr!"
  - "Quick, ask Digitalis about linked lists!"
  - "Ask for nicktatorship while you're at it!"